language: node_js

node_js:
- 'node'

os:
- linux

dist: trusty

env:
- TWEET_ENDPOINT=$TWEET_ENDPOINT

install:
- npm install -g typescript
- npm install -g gts
- npm install

script:
- npm run compile
- node out/index.js

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  # on:
  #   condition: $TRAVIS_EVENT_TYPE == 'cron'